---
- hosts: tag_env_production
  user: "{{ ansible_ssh_user }}"
  become: yes
  roles:
    - user
    - common
    - pip
    - role: docker
      docker_install_compose: true
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

- hosts: tag_env_production
  user: "{{ current_user }}"
  become: yes
  become_user: root
  roles:
    - backend
    - compose