name: Manual Action
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Run ansible
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract ansible vault password to file
        run: echo $VAULT_PASS > vault_password
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}

      - name: Create .ssh folder
        run: mkdir ~/.ssh

      - name: Decrypt ssh key encrypted file with ansible-vault
        run: ansible-vault view roles/user/files/dao.pem --vault-password-file vault_password > ~/.ssh/id_rsa

      - name: Update permissions on ssh key
        run: chmod 0600 ~/.ssh/id_rsa

      - name: Remove buggy ansible
        run: sudo apt remove ansible

      - name: Install python requirements for ec2 dynamic inventory
        run: python -m pip install -r requirements.txt

      - name: Install ansible galaxy requirements
        run: ansible-galaxy install -f -r roles/requirements.yml

      - name: Run ansible production playbook
        run: ansible-playbook -e env=$TRIGGER_BRANCH -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DOCKER_USERNAME=$DOCKER_USERNAME -e DOCKER_PASSWORD=$DOCKER_PASSWORD -e GH_TOKEN=$GH_TOKEN --vault-password-file vault_password -i inventories/production_aws_ec2.yml production.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}